#!/bin/bash
# createTxtFile "$pdf_path" "$pdf_dirname" "$pdf_filename"

# Absolute path to this script, e.g. /home/user/bin/foo.sh
# script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
# script_path=$(dirname "$script")
# script_name=$(basename "$script")

red="\e[0;31m"
green="\e[0;32m"
TOA="\e[0m" # No Color

function logError () {
  echo -e "${red}$1${TOA}" 1>&2
}

function logInfo () {
    echo -e "${green}$1${TOA}" 1>&2
}

pdf_path="$1"
pdf_dirname="$2"
pdf_filename="$3"

make_space=$(python -c 'print u"\u0001\u000C\u0009\u00A0\u2004\u2005\u2006\u2009\u200A\u200B".encode("utf8")')
# pdftotext "$pdf_path" "$pdf_dirname/$pdf_filename.txt"
# if [ $? -gt 0 ]; then 
#   logError "Fehler in der Verarbeitung, lösche txt-Dateien"
#   rm "$pdf_dirname/$pdf_filename.human-readable.txt"
#   rm "$pdf_dirname/$pdf_filename.txt"
#   exit 1;
# fi

if [ ! -f "$pdf_dirname/$pdf_filename.human-readable.txt" ]; then
  pdf2txt.py -o "$pdf_dirname/$pdf_filename.human-readable.txt" "$pdf_path"
  if [ $? -gt 0 ]; then 
    logError "Fehler in der Verarbeitung, lösche txt-Dateien"
    if [ -f "$pdf_dirname/$pdf_filename.human-readable.txt" ]; then
      rm "$pdf_dirname/$pdf_filename.human-readable.txt"
    fi
    if [ -f "$pdf_dirname/$pdf_filename.txt" ]; then
      rm "$pdf_dirname/$pdf_filename.txt"
    fi
    exit 1;
  fi
  # Erzwinge neu "$pdf_dirname/$pdf_filename.md5"
  logInfo "Erzwinge neu schreiben von \"$pdf_dirname/$pdf_filename.md5\"."
  md5_new_Pdf=$(md5sum "$pdf_path"  | gawk  -F ' ' '{print $1}')
  echo "$md5_new_Pdf" > "$pdf_dirname/$pdf_filename.md5"
fi

temp_file_1=$(tempfile)
temp_file_2=$(tempfile)
temp_file_3=$(tempfile)

logInfo "Schreibe \"$pdf_filename.txt\" neu."

# !!!!! Runde Klammern dürfen nicht angefasst werden, das gibt Probleme mit Bauarten und Achsfolgen !!!!!

sed -E ':a;N;$!ba;s/([a-z])\-\n([a-z])/\1\2/g' "$pdf_dirname/$pdf_filename.human-readable.txt" > "$temp_file_1"
sed -E ':a;N;$!ba;s/([a-zA-Z])(\-)\n([A-Z])/\1\2\3/g' "$temp_file_1" > "$temp_file_2"
sed ':a;N;$!ba;s/\n/ \n /g' "$temp_file_2" | sed 's/['"$make_space"']/ /g' | sed -e 's/\*[[:space:]]/ \* /g' | sed -e 's/\.[[:space:]]/ \. /g' | sed -e 's/\,[[:space:]]/ \, /g' | sed -e 's/\:[[:space:]]/ \: /g' | sed -e 's/\;[[:space:]]/ \; /g' | sed -E 's/\-/ - /g' | sed -E 's/([0-9])\-(.)/\1 - \2/g' | sed -E 's/[[:space:]]{2,}/ /g' | sed -E 's/([[:space:]]BR)([0-9])/\1 \2/g' > "$temp_file_3"
# Move the temporary file 
mv "$temp_file_3" "$pdf_dirname/$pdf_filename.txt"

exit 0
