#!/bin/bash

##
#
# Durchsucht ab "LibraryPath" alle Verzeichnisse nach "spellcheck_check_required"
# und bietet Aktionen an
#
# test_spell_check_required "PfadZumCalibreVerzeichnisOderUnterverzeichnis"
#
##

# Absolute path to this script, e.g. /home/user/bin/foo.sh
script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
script_path=$(dirname "$script")

cfg_log_level=$(look log_level "$script_path"/main.cfg | cut -d '=' -f 2-)
. "$script_path/libraries/logging.sh" "$cfg_log_level"

if [[ $cfg_log_level != "4" ]]; then
  cfg_log_level=3
fi

cfg_remove_not_found=$(look remove_not_found "$script_path"/main.cfg | cut -d '=' -f 2-)
cfg_dry_run=$(look dry_run "$script_path"/main.cfg | cut -d '=' -f 2-)

cfg_app_spellcheck=$(look app_spellcheck "$script_path"/main.cfg | cut -d '=' -f 2-)
if [[ -z $cfg_app_spellcheck ]]; then
  cfg_app_spellcheck="xdg-open"
fi

cfg_app_pdf_viewer=$(look app_pdf_viewer "$script_path"/main.cfg | cut -d '=' -f 2-)
if [[ -z $cfg_app_pdf_viewer ]]; then
  cfg_app_pdf_viewer="xdg-open"
fi

if [[ $cfg_remove_not_found == "0" ]]; then
  logWarn "In \"$script_path/main.cfg\" (remove_not_found) ist konfiguriert, dass bei einer Aktualisierung keine Schlüsselwörter entfernt werden."
fi
if [[ $cfg_dry_run == "1" ]]; then
  logWarn "In \"$script_path/main.cfg\" (dry_run) ist konfiguriert, dass bei einer Aktualisierung Schlüsselwörter weder hinzugefügt noch entfernt werden."
fi

# script_name=$(basename "$script")

library_path="$1"

if [[ -z $library_path ]]; then
  echo "Benutzung: $script_name \"PfadZurCalibreDbOderUnterverzeichnis\""
  exit 1
fi

files=$(find "$library_path" -type f -name "spellcheck_check_required")
logInfo "$(wc -l <<< "$files") Datei(en) gefunden"
echo "$files"
if [[ ! -z "$files" ]]; then
  while read file; do
    working_path=$(dirname "$file")
    human_readable_path=$(find "$working_path" -name "*human-readable.txt" | head -1)
    pdf_file_path=${human_readable_path//human-readable\.txt/pdf}

    echo
    echo "Rechtschreibprüfung"

    echo "1) Rechtschreibprüfung starten \"$human_readable_path\""
    echo "2) PDF ansehen \"$pdf_file_path\""
    echo "3) Aktualisierung der Schlüsselwörter durchführen"
    echo "8) Nichts tun"
    while true; do
      read -p "Bitte wählen: " input < /dev/tty
      case $input in
        [1]* )
          echo "Öffne \"$human_readable_path\""
          "$cfg_app_spellcheck" "$human_readable_path" > /dev/null 2>&1 &
          ;;
        [2]* )
          echo "Öffne \"$pdf_file_path\""
          "$cfg_app_pdf_viewer" "$pdf_file_path" > /dev/null 2>&1 &
          ;;
        [3]* )
        compressed_file_path=${human_readable_path//human-readable/compressed}
        if [[ -f "$compressed_file_path" ]]; then
          rm "$compressed_file_path"
        fi
        extract_and_write_keywords_into_calibre "$working_path"
        break;;
        [8]* ) break;;
        * ) echo "Ungültige Auswahl";;
      esac
    done

    echo
    echo "Die Datei \"$human_readable_path\" wurde in einer der letzten Aktualisierungen als \"Rechtschreibung testen\" markiert. Diesen Vermerk entfernen?"
    echo "n) Nein, nichts tun"
    echo "j) Ja, Vermerk entfernen"

    while true; do
      read -p "Bitte wählen: " input < /dev/tty
      case $input in
          n* )
            break;;
          j* )
            if [ -f "$file" ]; then
              rm "$file"
              logInfo "\"$file\" entfernt."
            fi
            break;;
          * ) echo "Ungültige Auswahl";;
      esac
    done
  done <<< "$files"
fi

exit 0
