#!/bin/bash

# Absolute path to this script, e.g. /home/user/bin/foo.sh
script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
script_path=$(dirname "$script")

red="\e[0;31m"
green="\e[0;32m"
yellow="\e[0;33m"
TOA="\e[0m" # No Color

function logInfo () {
    echo -e "${green}$1${TOA}"
}

function logWarn () {
  echo -e "${yellow}$1${TOA}"
}

function logError () {
  echo -e "${red}$1${TOA}"
}

baureihe="$1"

if [ ! -f "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern" ]; then
  if [[ $baureihe == E* ]] || [[ $baureihe == V* ]]; then
    cp "$script_path/../human_readable_pattern/standard/test-BR_YYXX.human_readable.pattern.template" "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
    yy=$(sed "s/[0-9]*//g" <<< "$baureihe")
    xx=$(sed "s/[A-Z]*//g" <<< "$baureihe")

    sed -i "s/YY/$yy/g" "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
    sed -i "s/XX/$xx/g" "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
  else
    cp "$script_path/../human_readable_pattern/standard/test-BR_XXX.human_readable.pattern.template" "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
    sed -i "s/XXX/$baureihe/g" "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
  fi
  if [ -f "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern" ]; then
    logInfo "neue Datei: \"$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern\""
  fi
else
  logWarn "\"$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern\" existiert bereits"
fi

if [ ! -f "$script_path/../tests/standard/test-BR_$baureihe.negative.001.list" ]; then
  if [[ $baureihe == E* ]] || [[ $baureihe == V* ]]; then
    touch "$script_path/../tests/standard/test-BR_$baureihe.negative.001.list"
  else
    cp "$script_path/../tests/standard/test-BR_XXX.negative.001.list.template" "$script_path/../tests/standard/test-BR_$baureihe.negative.001.list"
    sed -i "s/XXX/$baureihe/g" "$script_path/../tests/standard/test-BR_$baureihe.negative.001.list"
  fi
  if [ -f "$script_path/../tests/standard/test-BR_$baureihe.negative.001.list" ]; then
    logInfo "neue Datei: \"$script_path/../tests/standard/test-BR_$baureihe.negative.001.list\""
  fi
else
  logWarn "\"$script_path/../tests/standard/test-BR_$baureihe.negative.001.list\" existiert bereits"
fi

if [ ! -f "$script_path/../tests/standard/test-BR_$baureihe.ods" ]; then
  if [[ $baureihe == E* ]] || [[ $baureihe == V* ]]; then
    cp "$script_path/../tests/standard/test-BR_YYXX.ods.template" "$script_path/../tests/standard/test-BR_$baureihe.ods"
  else
    cp "$script_path/../tests/standard/test-BR_XXX.ods.template" "$script_path/../tests/standard/test-BR_$baureihe.ods"
  fi
  if [ -f "$script_path/../tests/standard/test-BR_$baureihe.ods" ]; then
    logInfo "neue Datei: \"$script_path/../tests/standard/test-BR_$baureihe.ods\""
  fi
else
  logWarn "\"$script_path/../tests/standard/test-BR_$baureihe.ods\" existiert bereits"
fi

if [ ! -f "$script_path/../tests/standard/test-BR_$baureihe.positive.001.list" ]; then
  cp "$script_path/../tests/standard/test-BR_XXX.positive.001.list.template" "$script_path/../tests/standard/test-BR_$baureihe.positive.001.list"
  if [ -f "$script_path/../tests/standard/test-BR_$baureihe.positive.001.list" ]; then
    logInfo "neue Datei: \"$script_path/../tests/standard/test-BR_$baureihe.positive.001.list\""
  fi
else
  logWarn "\"$script_path/../tests/standard/test-BR_$baureihe.positive.001.list\" existiert bereits"
fi

if [ ! -f "$script_path/../tests/standard/test-BR_$baureihe.positive.002.list" ]; then
  cp "$script_path/../tests/standard/test-BR_XXX.positive.002.list.template" "$script_path/../tests/standard/test-BR_$baureihe.positive.002.list"
  if [ -f "$script_path/../tests/standard/test-BR_$baureihe.positive.002.list" ]; then
    logInfo "neue Datei: \"$script_path/../tests/standard/test-BR_$baureihe.positive.002.list\""
  fi
else
  logWarn "\"$script_path/../tests/standard/test-BR_$baureihe.positive.002.list\" existiert bereits"
fi

echo "Dateien werden zur Bearbeitung geöffnet"
echo "w) Dateien öffnen"
echo "q) ohne Bearbeitung fortfahren"
while true; do
  read -p "Bitte wählen: " input < /dev/tty
  case $input in
      [w]* )
        xdg-open "$script_path/../tests/standard/test-BR_$baureihe.ods" > /dev/null 2>&1
        xdg-open "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern" > /dev/null 2>&1
        xdg-open "$script_path/../tests/standard/test-BR_$baureihe.positive.002.list" > /dev/null 2>&1
        xdg-open "$script_path/../tests/standard/test-BR_$baureihe.positive.001.list" > /dev/null 2>&1
        break;;
      [q]* )
        break;;
      * ) echo "Ungültige Auswahl";;
  esac
done

echo "Tests werden durchgeführt"
echo "w) Tests starten"
echo "q) ohne Tests fortfahren"
while true; do
  read -p "Bitte wählen: " input < /dev/tty
  case $input in
      [w]* )
        awk '/^$/{ if (! blank++) print; next } { blank=0; print }' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
        /home/aboettger/src/RailroadKeywords/create_railroad_keywords_from_pdf test /home/aboettger/src/RailroadKeywords/pattern/test-BR_"$baureihe".pattern
        break;;
      [q]* )
        break;;
      * ) echo "Ungültige Auswahl";;
  esac
done

echo "Geänderte Dateien zur Versionskontrolle hinzufügen und auf Server veröffentlichen"
echo "w) zur Versionskontrolle hinzufügen"
echo "q) ohne Versionskontrolle fortfahren"
while true; do
  read -p "Bitte wählen: " input < /dev/tty
  case $input in
      [w]* )
        cd "$script_path/../"
        git add --all
        git commit -a -m "Baureihe $baureihe hinzugefügt"
        break;;
      [q]* )
        break;;
      * ) echo "Ungültige Auswahl";;
  esac
done
