#!/bin/bash

# Absolute path to this script, e.g. /home/user/bin/foo.sh
script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
script_path=$(dirname "$script")

cfg_log_level=$(look log_level "$script_path"/../main.cfg | cut -d '=' -f 2-)
. "$script_path/../libraries/logging.sh" "$cfg_log_level"

if [[ $cfg_log_level != "4" ]]; then
  cfg_log_level=3
fi

baureihe="$1"

function startCreate () {
  if [ ! -f "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern" ]; then
    if [[ $baureihe == D* ]] || [[ $baureihe == E* ]] || [[ $baureihe == V* ]]; then
      cp "$script_path/../human_readable_pattern/standard/test-BR_YYXX.human_readable.pattern.template" "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
      yy=$(sed -e "s/[0-9]*//g" <<< "$baureihe")
      xx=$(sed -e "s/[A-Z]*//g" <<< "$baureihe")

      if [[ $baureihe == V ]]; then
        echo "pattern_delete=(.*km\/h.*)" >> "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
        echo "pattern_not_merge=([[:space:]]YY[[:space:]]{0,1}XX(|[[:space:]]*km\/h)[[:space:]])" >> "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
      else
        echo "pattern_not_merge=([[:space:]]YY[[:space:]]{0,1}XX[[:space:]])" >> "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
      fi

      sed -i "s/YY/$yy/g" "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
      sed -i "s/XX/$xx/g" "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"

    else
      cp "$script_path/../human_readable_pattern/standard/test-BR_XXX.human_readable.pattern.template" "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
      sed -i "s/XXX/$baureihe/g" "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
    fi
    if [ -f "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern" ]; then
      logInfo "neue Datei: \"$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern\""
    fi
  else
    logWarn "\"$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern\" existiert bereits"
  fi

  if [ ! -f "$script_path/../tests/standard/test-BR_$baureihe.negative.001.list" ]; then
    if [[ $baureihe == D* ]] || [[ $baureihe == E* ]] || [[ $baureihe == V* ]]; then
      touch "$script_path/../tests/standard/test-BR_$baureihe.negative.001.list"
    else
      cp "$script_path/../tests/standard/test-BR_XXX.negative.001.list.template" "$script_path/../tests/standard/test-BR_$baureihe.negative.001.list"
      sed -i "s/XXX/$baureihe/g" "$script_path/../tests/standard/test-BR_$baureihe.negative.001.list"
    fi
    if [ -f "$script_path/../tests/standard/test-BR_$baureihe.negative.001.list" ]; then
      logInfo "neue Datei: \"$script_path/../tests/standard/test-BR_$baureihe.negative.001.list\""
    fi
  else
    logWarn "\"$script_path/../tests/standard/test-BR_$baureihe.negative.001.list\" existiert bereits"
  fi

  if [ ! -f "$script_path/../tests/standard/test-BR_$baureihe.ods" ]; then
    if [[ $baureihe == D* ]] || [[ $baureihe == E* ]] || [[ $baureihe == V* ]]; then
      cp "$script_path/../tests/standard/test-BR_YYXX.ods.template" "$script_path/../tests/standard/test-BR_$baureihe.ods"
    else
      cp "$script_path/../tests/standard/test-BR_XXX.ods.template" "$script_path/../tests/standard/test-BR_$baureihe.ods"
    fi
    if [ -f "$script_path/../tests/standard/test-BR_$baureihe.ods" ]; then
      logInfo "neue Datei: \"$script_path/../tests/standard/test-BR_$baureihe.ods\""
    fi
  else
    logWarn "\"$script_path/../tests/standard/test-BR_$baureihe.ods\" existiert bereits"
  fi

  if [ ! -f "$script_path/../tests/standard/test-BR_$baureihe.positive.001.list" ]; then
    cp "$script_path/../tests/standard/test-BR_XXX.positive.001.list.template" "$script_path/../tests/standard/test-BR_$baureihe.positive.001.list"
    if [ -f "$script_path/../tests/standard/test-BR_$baureihe.positive.001.list" ]; then
      logInfo "neue Datei: \"$script_path/../tests/standard/test-BR_$baureihe.positive.001.list\""
    fi
  else
    logWarn "\"$script_path/../tests/standard/test-BR_$baureihe.positive.001.list\" existiert bereits"
  fi

  if [ ! -f "$script_path/../tests/standard/test-BR_$baureihe.positive.002.list" ]; then
    cp "$script_path/../tests/standard/test-BR_XXX.positive.002.list.template" "$script_path/../tests/standard/test-BR_$baureihe.positive.002.list"
    if [ -f "$script_path/../tests/standard/test-BR_$baureihe.positive.002.list" ]; then
      logInfo "neue Datei: \"$script_path/../tests/standard/test-BR_$baureihe.positive.002.list\""
    fi
  else
    logWarn "\"$script_path/../tests/standard/test-BR_$baureihe.positive.002.list\" existiert bereits"
  fi
  echo "startOpen"
}

# 1
function startOpen () {
  echo >&2
  echo >&2 "Dateien werden zur Bearbeitung geöffnet"
  echo >&2 "w) Dateien öffnen"
  echo >&2 "d) Alle Dateien des Typs \"$baureihe\", die durch dieses Programm angelegt wurden, löschen und beenden"
  echo >&2 "q) ohne Bearbeitung fortfahren"
  echo >&2 "b) zurück zum Erstellen der Dateien"
  while true; do
    read -p "Bitte wählen: " input < /dev/tty
    case "$input" in
        [w]* )
          xdg-open "$script_path/../tests/standard/test-BR_$baureihe.ods" > /dev/null 2>&1
          xdg-open "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern" > /dev/null 2>&1
          xdg-open "$script_path/../tests/standard/test-BR_$baureihe.positive.002.list" > /dev/null 2>&1
          xdg-open "$script_path/../tests/standard/test-BR_$baureihe.positive.001.list" > /dev/null 2>&1
          echo "startTest"
          break;;
        [d]* )
          rm "$script_path/../tests/standard/test-BR_$baureihe.ods"
          rm "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern"
          rm "$script_path/../tests/standard/test-BR_$baureihe.positive.002.list"
          rm "$script_path/../tests/standard/test-BR_$baureihe.positive.001.list"
          echo "startQuit"
          break;;
        [q]* )
          echo "startTest"
          break;;
        [b]* )
          echo "startCreate"
          break;;
        * ) echo >&2 "Ungültige Auswahl";;
    esac
  done
}

# 2
function startTest () {
  echo >&2
  echo >&2 "Tests werden durchgeführt"
  echo >&2 "w) Tests starten"
  echo >&2 "q) ohne Tests fortfahren"
  echo >&2 "b) zurück zum Öffnen der Dateien"
  while true; do
    read -p "Bitte wählen: " input < /dev/tty
    case "$input" in
        [w]* )
          awk '/^$/{ if (! blank++) print; next } { blank=0; print }' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[0123456789\]/[0-9]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[012345678\]/[0-8]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[01234567\]/[0-7]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[0123456\]/[0-6]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[012345\]/[0-5]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[01234\]/[0-4]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[0123\]/[0-3]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[012\]/[0-2]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          
          sed -e 's/\[123456789\]/[1-9]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[12345678\]/[1-8]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[1234567\]/[1-7]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[123456\]/[1-6]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[12345\]/[1-5]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[1234\]/[1-4]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[123\]/[1-3]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          
          sed -e 's/\[23456789\]/[2-9]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[2345678\]/[2-8]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[234567\]/[2-7]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[23456\]/[2-6]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[2345\]/[2-5]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[234\]/[2-4]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern

          sed -e 's/\[3456789\]/[3-9]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[345678\]/[3-8]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[34567\]/[3-7]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[3456\]/[3-6]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[345\]/[3-5]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          
          sed -e 's/\[456789\]/[4-9]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[45678\]/[4-8]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[4567\]/[4-7]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[456\]/[4-6]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          
          sed -e 's/\[56789\]/[5-9]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[5678\]/[5-8]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[567\]/[5-7]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          
          sed -e 's/\[6789\]/[6-9]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          sed -e 's/\[678\]/[6-8]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern
          
          sed -e 's/\[789\]/[7-9]/g' /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern  > ~/tmp/test-BR_"$baureihe".human_readable.pattern; mv ~/tmp/test-BR_"$baureihe".human_readable.pattern /home/aboettger/src/RailroadKeywords/human_readable_pattern/standard/test-BR_"$baureihe".human_readable.pattern

          /home/aboettger/src/RailroadKeywords/create_railroad_keywords_from_pdf test /home/aboettger/src/RailroadKeywords/pattern/test-BR_"$baureihe".pattern >&2
          echo "startGit"
          break;;
        [q]* )
          echo "startGit"
          break;;
        [b]* )
          echo "startOpen"
          break;;
        * ) echo >&2 "Ungültige Auswahl";;
    esac
  done
}

# 3
function startGit () {
  echo >&2
  echo >&2 "Geänderte Dateien zur Versionskontrolle hinzufügen und auf Server veröffentlichen"
  echo >&2 "w) zur Versionskontrolle hinzufügen"
  echo >&2 "q) ohne Versionskontrolle fortfahren"
  echo >&2 "b) zurück zum Testen"
  while true; do
    read -p "Bitte wählen: " input < /dev/tty
    case "$input" in
        [w]* )
          cd "$script_path/../"
          git add "$script_path/../tests/standard/test-BR_$baureihe.negative.001.list" \
            "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern" \
            "$script_path/../tests/standard/test-BR_$baureihe.positive.002.list" \
            "$script_path/../tests/standard/test-BR_$baureihe.positive.001.list" >&2
          git commit -o "$script_path/../tests/standard/test-BR_$baureihe.negative.001.list" \
            "$script_path/../human_readable_pattern/standard/test-BR_$baureihe.human_readable.pattern" \
            "$script_path/../tests/standard/test-BR_$baureihe.positive.002.list" \
            "$script_path/../tests/standard/test-BR_$baureihe.positive.001.list" \
            -m "Baureihe $baureihe hinzugefügt" >&2
          echo "startQuit"
          break;;
        [q]* )
          echo "startQuit"
          break;;
        [b]* )
          echo "startTest"
          break;;
        * ) echo >&2 "Ungültige Auswahl";;
    esac
  done
}

retValue=$(startCreate)
while true; do
  case $retValue in
      "startCreate")
        retValue=$(startCreate)
        ;;
      "startOpen")
        retValue=$(startOpen)
        ;;
      "startTest")
        retValue=$(startTest)
        ;;
      "startGit")
        retValue=$(startGit)
        ;;
      "startQuit")
        break;;
      *) break;;
  esac
done


exit 0
