#!/bin/bash
# Thanks: https://github.com/l0b0/txt2cloud

library_path="$1"
output_path="$2"

min_font_size="1";

json=$(calibredb list --fields tags --for-machine --library-path "$library_path")
count_entries=$(echo "$json" | jshon -l)
count_entries=$((count_entries-1))
for i in $(seq 0 "$count_entries"); do
  echo -ne "Processing $i/$count_entries\033[K\r"
  keysForCounter=$(echo "$json" | jshon -e "$i" -e "tags" | tr -d "[" | tr -d "]" | tr -d "," | tr -d "\"" | sed 's/\\//')
  if [ ! -z "$keysForCounter" ]; then
    keysForCounter=$(echo "$keysForCounter" | sed -e 's/^ *//' | sed -e 's/ *$//')
    keys="$keys$keysForCounter"
  fi
done

IFS=$'\n'
unique_keys=$(echo "$keys" | sort | uniq)

if [ -f "$output_path" ]; then
  rm "$output_path"
fi

echo '<?xml version="1.0" encoding="UTF-8"?>' >> "$output_path"
echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">' >> "$output_path"
echo '<html xmlns="http://www.w3.org/1999/xhtml">' >> "$output_path" 
echo '<head>' >> "$output_path"
echo '<title>Tag Cloud</title>' >> "$output_path"
echo '</head>' >> "$output_path"
echo '<body>' >> "$output_path"
echo '<div class="cloud" style="text-align:justify">' >> "$output_path"
for key in $unique_keys; do
  echo -ne "Processing $key\033[K\r"
  keyCount=$(echo "$keys" | grep -cow "$key")
  key=$(echo "$key" | sed -e 's/ /\&nbsp;/')
  # Font size (minimum 1)
  font_size=$(echo "l(${keyCount} - ${min_font_size-0} + 1) + 1" | bc -l)
  echo -n "<span style='margin:0em 0.5em 0em 0.5em; font-size:${font_size}em'>$key</span> " >> "$output_path"
done
echo '</div>' >> "$output_path"
echo '</body>' >> "$output_path"
echo '</html>' >> "$output_path"
