#!/bin/bash

# Absolute path to this script, e.g. /home/user/bin/foo.sh
script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
script_path=$(dirname "$script")

find "$script_path/../human_readable_pattern" -type f -name "test-*.human_readable.pattern" | sort | { while read -r file;
do
  output_filename=${file//human_readable.pattern/pattern}
  output_filename=${output_filename//human_readable_pattern/pattern}
  sed '/^\#/d' "$file" | sed '/^$/d' | sed ':a;N;$!ba;s/\npattern=/|/g' > "$output_filename"
done }
