#!/bin/bash

# Absolute path to this script, e.g. /home/user/bin/foo.sh
script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
script_path=$(dirname "$script")

cfg_log_level=$(look log_level "$script_path"/../main.cfg | cut -d '=' -f 2-)
. "$script_path/../libraries/logging.sh" "$cfg_log_level"

sed -e "s/xx/$1/g" < "$script_path/../all/BR XX 0 - BR XX 9999.template" > "$script_path/../all/$2.all.002.txt"
sed -e "s/xx/$1/g" < "$script_path/../all/BR XX.0 - BR XX.99.template" > "$script_path/../all/$2.all.001.txt"

logDebug "$script_path/../all/$2.all.001.txt"
logDebug "$script_path/../all/$2.all.002.txt"

# Für Fahrzeuge mit V, E, VT erzeuge ich keine Schlüsselwörter in der Art "BR E 01" oder "BR E01"
if [[ $1 == D* ]] || [[ $1 == E* ]] || [[ $1 == V* ]]; then
  sed -i "s/[[:space:]]BR.*//g" "$script_path/../all/$2.all.001.txt"
fi

exit 0
