#!/bin/bash
# Durchsucht die Dateien im Verzeichnis "tests" nach sehr kurzen Wörtern und fügt sie einer Liste hinzu
# Diese Liste kann mit "tools/grep_potentially_false_positive" verwendet werden, um sie zu überprüfen

# Absolute path to this script, e.g. /home/user/bin/foo.sh
script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
script_path=$(dirname "$script")

output_file="$script_path/../false_positive/potentially_false_positive"

if [ -f "$output_file" ]; then
  rm "$output_file"
fi


find "$script_path/../tests" -type f -name "*.positive*.list" | sort | { while read -r file;
  do
    echo "$file"
    sed '/^\#/d' "$file" | sed '/^$/d' | { while read -r line; do
      line=$(sed 's/^ *//g' <<< "$line" | sed 's/ *$//g')
      line_without_spaces=$(sed 's/ *//g' <<< "$line")
      test_uppercases=$(grep "^[A-Z]*\$" <<< "$line_without_spaces")
      if [[ $test_uppercases != "" ]]; then
        echo "$line" >> "$output_file"
      fi
      
      
      # if [[ $len_compressed_line -gt 0 ]] && [[ $len_compressed_line -lt 3 ]]; then
      #   echo "$line" >> "$output_file"
      # fi
      
      if [[ $line == *.* ]]; then
        var1=$(echo "$line" | cut -f1 -d.)
        var2=$(echo "$line" | cut -f2 -d.)
        size1=${#var1}
        size2=${#var2}
        if [ "$size1" -gt "0" ] && [ "$size1" -lt "3" ] && [ "$size2" -gt "0" ] && [ "$size2" -lt "3" ] ; then
          if [ "$var1" -gt "0" ] && [ "$var1" -lt "32" ] && [ "$var2" -gt "0" ] && [ "$var2" -lt "13" ] ; then
            echo "$line" >> "$output_file"
          fi
        fi
      fi
    done
  }
  done
}

{
  echo "50er"
  echo "60er"
  echo "70er"
  echo "80er"
  echo "90er"
} >> "$output_file"

if [ -f "$output_file" ]; then
  tmp_file=$(mktemp)
  echo "# Diese Datei wird automatisch durch \"$script\" erstellt." > "$tmp_file"
  sort "$output_file" | uniq >> "$tmp_file"
  mv "$tmp_file" "$output_file"
fi

echo "Ergebnis abgelegt in: \"$script_path/../false_positive/potentially_false_positive\""

exit 0
