#!/bin/bash
# Durchsucht die Dateien im Verzeichnis "tests" nach sehr kurzen Wörtern und fügt sie einer Liste hinzu
# Diese Liste kann mit "tools/grep_potentially_false_positive" verwendet werden, um sie zu überprüfen

# Absolute path to this script, e.g. /home/user/bin/foo.sh
script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
script_path=$(dirname "$script")

cfg_log_level=$(look log_level "$script_path"/../main.cfg | cut -d '=' -f 2-)
. "$script_path/../libraries/logging.sh" "$cfg_log_level"

output_file="$script_path/../false_positive/potentially_false_positive"

if [ -f "$output_file" ]; then
  rm "$output_file"
fi


find "$script_path/../tests" -type f -name "*.list" | sort | { while read file;
  do
    echo "$file"
    sed -e '/^ *#.*/d' "$file" | sed -e '/^ *$/d' | { while read line; do
      line=$(sed -e 's/^ *//g' <<< "$line" | sed -e 's/ *$//g')

      result=$(grep -oE "^[A-Z] [A-Z]\$" <<< "$line")
      # echo "$line"
      if [[ $result != "" ]]; then
        echo "$line" >> "$output_file"
      else
        result=$(grep -oE "^((0[1-9])|([1-2][0-9])|(3[01]))\.((0[1-9])|(1[012]))\$" <<< "$line")
        if [[ $result != "" ]]; then
          echo "$line" >> "$output_file"
        else
          result=$(grep -oE "^[5-9]0er\$" <<< "$line")
          if [[ $result != "" ]]; then
            echo "$line" >> "$output_file"
          fi
        fi
      fi
    done
  }
  done
}

if [ -f "$output_file" ]; then
  tmp_file=$(mktemp)
  echo "# Diese Datei wird automatisch durch \"$script\" erstellt." > "$tmp_file"
  sort "$output_file" | uniq >> "$tmp_file"
  mv "$tmp_file" "$output_file"
fi

echo "Ergebnis abgelegt in: \"$script_path/../false_positive/potentially_false_positive\""

exit 0
