#!/bin/bash
# Durchsucht die Dateien im Verzeichnis "tests" nach sehr kurzen Wörtern und fügt sie einer Liste hinzu
# Diese Liste kann mit "tools/grep_potentially_false_positive" verwendet werden, um sie zu überprüfen

# Absolute path to this script, e.g. /home/user/bin/foo.sh
script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
script_path=$(dirname "$script")

output_file="$script_path/../false_positive/potentially_false_positive"

if [ -f "$output_file" ]; then
  rm "$output_file"
fi



find "$script_path/../tests" -type f -name "*.positive*.list" | sort | { while read -r file;
  do
    echo "$file"
    cat "$file" | { while read -r line; do
      compressed_line=$(echo "$line" | tr -d ' ')
      len_compressed_line=$(echo ${#compressed_line})
      if [ "$len_compressed_line" -gt 0 ] && [ "$len_compressed_line" -lt 3 ]; then
        echo "$line" >> "$output_file"
      fi
    done
  }
  done
}

if [ -f "$output_file" ]; then
  tmp_file=$(mktemp)
  echo "# Diese Datei wird automatisch durch \"$script\" erstellt." > "$tmp_file"
  sort "$output_file" | uniq >> "$tmp_file"
  mv "$tmp_file" "$output_file"
fi

exit 0
