#! /bin/bash

# Absolute path to this script, e.g. /home/user/bin/foo.sh
script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
script_path=$(dirname "$script")

cfg_log_level=$(look log_level "$script_path"/../main.cfg | cut -d '=' -f 2-)
. "$script_path/../libraries/logging.sh" "$cfg_log_level"

shopt -s nullglob
shopt -s nocaseglob
find "$1" -depth  -type d | { while read -r D;
  do
    case "$D" in
      "$DR" ) continue;;
    esac
    pdfs=$(echo "$D"/*.pdf)
    txts=$(echo "$D"/*compressed.txt)
    if [ "$txts" == "" ] && [ "$pdfs" != "" ]; then
       echo "$pdfs"
    fi
done }

exit 0
