#!/bin/bash

# Absolute path to this script, e.g. /home/user/bin/foo.sh
script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
script_path=$(dirname "$script")

script_name=$(basename "$script")

red="\e[0;31m"
green="\e[0;32m"
yellow="\e[0;33m"
TOA="\e[0m" # No Color

function logInfo () {
    echo -e "${green}$1${TOA}"
}

function logWarn () {
  echo -e "${yellow}$1${TOA}"
}

function logError () {
  echo -e "${red}$1${TOA}"
}

library_path="$1"
keyword="$2"

if [ -z "$keyword" ] || [ -z "$library_path" ]; then
  echo "Benutzung: $script_name \"[PfadZurCalibreDB]\" \"[Schlüsselwort]\""
  exit 1
fi

search_for="'tags:\"~^$keyword\$\"'"
result=$(eval calibredb list --for-machine --library-path "$library_path" --fields=tags -s "$search_for")
calibre_ids=$(awk -F"\"id\": " '{print $2}' <<< "$result" | sed 's/,//g' | sed '/^$/d')

while read -r calibre_id; do
  # echo "$calibre_id"
  metadata_files=$(find "$1" -type f -name "metadata.opf")
  while read -r metadata_file; do
    # xpath -q -e "//package/metadata/dc:identifier[@id='calibre_id']/text()" "$metadata_path"
    metadata_path=$(grep -l "<dc:identifier opf:scheme=\"calibre\" id=\"calibre_id\">$calibre_id</dc:identifier>" "$metadata_file")
    if [[ $metadata_path != "" ]]; then
      working_path=$(dirname "$metadata_path")
      break
    fi
  done <<< "$metadata_files"

  pattern_files=$(find "$script_path"/../pattern -type f -name "test-UIC.pattern")
  pattern_files_hit=$(
    while read pattern_file; do
    pattern=$(sed '/^#/d' "$pattern_file" | grep 'pattern=' | gawk  -F 'pattern=' '{print $2}' | sed 's/(/\\(/g' | sed 's/)/\\)/g' | sed 's/|/\\|/g')
    result=$(grep "$pattern" <<< " $keyword ")
    if [[ $result != "" ]]; then
      echo "$pattern_file"
    fi
    done <<< "$pattern_files"
  )
  # echo "$pattern_files_hit"
  
  echo
  echo -e "${green}$keyword${TOA} für Calibre-ID ${green}$calibre_id${TOA} gefunden durch:"
  echo "$pattern_files_hit"
  
  dont_ask_file=""
  ignore_file=""
  while read pattern_file_hit; do
    # echo "$pattern_file_hit"
    false_positive_file=${pattern_file_hit//pattern\//false_positive\/}
    # echo "$false_positive_file"
    true_positive_file=${pattern_file_hit//pattern\//true_positive\/}
    true_positive_file=${true_positive_file//pattern/list}
    # echo "$true_positive_file"

    if [ -f "$true_positive_file" ]; then
      true_positive=$(grep -l "^$calibre_id=$keyword\$" "$true_positive_file")
    else
      true_positive=""
    fi
    if [ ! -z "$true_positive" ]; then
      echo "\"$keyword\" für Calibre-ID $calibre_id  wurde in \"$true_positive\" gefunden, keine Aktion nötig."
    else
      keywords_pattern=$(sed -E 's/^(.*)$/[[:space:]]\1[[:space:]]/g' <<< "$keyword")

      pdf_path=$(find "$working_path" -type f -name '*.pdf')
      pdf_name=$(basename "$pdf_path")
      hr_txt_path=${pdf_path//.pdf/.human-readable.txt}
      txt_path=${pdf_path//.pdf/.txt}

      pattern_file_name="$(basename "$false_positive_file")"
      human_readable_file_name=${pattern_file_name//.pattern/.human_readable.pattern}

      echo
      echo "Bitte Entscheidung treffen für:"
      logInfo "$pattern_file_hit"
      echo
      egrep -anET -C 5 "$keywords_pattern" "$txt_path"

      keyword_pattern=$(sed -e 's/\//\\\//g' <<< "$keyword")
      ignore_file="$false_positive_file"
      dont_ask_file="$true_positive_file"

      echo
      echo "1) Nicht mehr fragen"
      echo "2) Schlüsselwort dauerhaft entfernen"
      echo "3) PDF ansehen"
      echo "4) TXT ansehen"
      echo "5) Verzeichnis öffnen (\"$working_path\")"
      echo "6) Nichts tun"
      while true; do
        read -p "Bitte wählen: " input < /dev/tty
        case $input in
            [1]* )
              echo "$calibre_id=$keyword" >> "$dont_ask_file"
              echo -e "Nach \"$keyword\" für Calibre-ID \"$calibre_id\" wird nicht mehr gefragt: ${green}$calibre_id=$keyword${TOA} in \"$dont_ask_file\""
              break;;
            [2]* )
              echo "$calibre_id=^($keyword_pattern)\$" >> "$ignore_file"
              extract_and_write_keywords_into_calibre "$working_path"
              echo -e "\"$keyword\" für Calibre-ID \"$calibre_id\" wurde dauerhaft entfernt: ${green}$calibre_id=^($keyword_pattern)\$${TOA} in \"$ignore_file\""
              break;;
            [3]* )
              echo "Öffne \"$pdf_path\""
              xdg-open "$pdf_path" > /dev/null 2>&1
              ;;
            [4]* )
              echo "Öffne \"$hr_txt_path\""
              xdg-open "$hr_txt_path" > /dev/null 2>&1
              ;;
            [5]* )
              echo "Öffne \"$working_path\""
              xdg-open "$working_path" > /dev/null 2>&1
              ;;
            [6]* ) break;;
            * ) echo "Ungültige Auswahl";;
        esac
      done
    fi
  done <<< "$pattern_files_hit"
done <<< "$calibre_ids"

exit 0
