#!/bin/bash

##
#
# Sucht in Calibre nach Schlüsselwörtern und bietet dazu gehörige Aktionen an.
# 
# tools/grep_potentially_false_positive "PfadZumCalibreVerzeichnisOderUnterverzeichnis" "ZuSuchendesSchlüsselwort"
#
##

# Absolute path to this script, e.g. /home/user/bin/foo.sh
script=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
script_path=$(dirname "$script")

cfg_log_level=$(look log_level "$script_path"/../main.cfg | cut -d '=' -f 2-)
. "$script_path/../libraries/logging.sh" "$cfg_log_level"

script_name=$(basename "$script")

category_separator=$(look category_separator "$script_path"/../main.cfg | cut -d '=' -f 2-)

library_path="$1"
keyword="$3"
given_category="$2"

if [ -z "$keyword" ] || [ -z "$library_path" ] || [ -z "$given_category" ]; then
  echo "Benutzung: $script_name \"PfadZurCalibreDBOderUnterverzeichnis\" \"Kategorie\" \"Schlüsselwort\""
  echo "Als Kategorie kann auch das Wildcard * verwendet werden."
  exit 1
fi

if [[ $given_category == "*" ]]; then 
  given_category=""
fi

if [ -f "$1" ]; then
  search_root=$(dirname "$1")
else
  search_root="$1"
fi

if [ "$search_root" == "." ]; then
  search_root=$(pwd)
fi

logInfo "Suche Calibre-DB (metadata.db)…"

calibreDbSearchPath="$search_root"
while [ ! -f "$calibreDbSearchPath/metadata.db" ] && [ "$calibreDbSearchPath" != "/" ]; do
  logInfo "$calibreDbSearchPath"
  calibreDbSearchPath=$(dirname "$calibreDbSearchPath")
done

if [ -f "$calibreDbSearchPath/metadata.db" ]; then
  logInfo "Calibre-DB (metadata.db) gefunden: \"$calibreDbSearchPath/metadata.db\""
else
  logError "Calibre-DB (metadata.db) nicht gefunden"
  cleanup
  exit 1
fi

# Wenn ein konkreter Buchpfad in der Calibre-DBgewält wurde, dann dessen
# Calibre-ID übernehmen
search_for="tags:\"~"
if [[ $given_category != "" ]]; then
  search_for="$search_for^$given_category\\$category_separator"
else
  search_for="$search_for$given_category\\$category_separator"
fi
keyword_search_for=$(sed -e 's/\./\\./g' <<< "$keyword")
search_for="$search_for$keyword_search_for\$\""
if [[ -f "$library_path/metadata.opf" ]]; then
  calibre_id=$(xpath -q -e "//package/metadata/dc:identifier[@id='calibre_id']/text()" "$library_path/metadata.opf")
  search_for="$search_for AND id:\"=$calibre_id\""
fi

logDebug "Suche mittels \"$search_for\" in Calibre"
result=$(eval calibredb list --for-machine --library-path "\"$calibreDbSearchPath\" " --fields=tags -s "'$search_for'")

if [[ $result == "[]" ]]; then
  echo "Keine Ergebnisse gefunden"
  exit 1
fi

calibre_ids=$(awk -F"\"id\": " '{print $2}' <<< "$result" | sed -e 's/,//g' | sed -e '/^$/d')

countCalibreIds=$(wc -l <<< "$calibre_ids")
count=0

if [[ ! -z $given_category ]]; then
  pattern_files=$(find "$script_path"/../pattern -type f -exec grep -q "^category=$given_category\$" {} \; -print)
else
  pattern_files=$(find "$script_path"/../pattern -type f -name "*.pattern")
fi

pattern_files_hit=$(
  logDebug "Suche passende Pattern-Datei"
  while read pattern_file; do
    if [[ ! -z $pattern_file ]]; then

      keyword_for_pattern=$(sed -e "s/^$category//" <<< "$keyword" | sed -e "s/-/ - /")
      keyword_for_pattern=$(sed -e "s/^\\$category_separator//" <<< "$keyword_for_pattern")
      
      patterns=$("$script_path/../functions/getPattern.sh" "$pattern_file")
      
      
      while read -r pattern; do
        result=$(grep -E "$pattern" <<< " $keyword_for_pattern ")
        if [[ $result != "" ]]; then
          echo "$pattern_file"
        fi
      done <<< "$patterns"
    fi
  done <<< "$pattern_files"
)

pattern_files_hit=$(sed -e '/^$/d' <<< "$pattern_files_hit")

while read -r calibre_id; do
  count=$((count+1))
  metadata_files=$(find "$library_path" -type f -name "metadata.opf")
  while read -r metadata_file; do
    # xpath -q -e "//package/metadata/dc:identifier[@id='calibre_id']/text()" "$metadata_path"
    metadata_path=$(grep -l "<dc:identifier opf:scheme=\"calibre\" id=\"calibre_id\">$calibre_id</dc:identifier>" "$metadata_file")
    if [[ $metadata_path != "" ]]; then
      working_path=$(dirname "$metadata_path")
      break
    fi
  done <<< "$metadata_files"

  # if [[ ! -z $given_category ]]; then
  #   pattern_files=$(find "$script_path"/../pattern -type f -exec grep -q "^category=$given_category\$" {} \; -print)
  # else
  #   pattern_files=$(find "$script_path"/../pattern -type f -name "*.pattern")
  # fi
  # 
  # pattern_files_hit=$(
  #   logDebug "Suche passende Pattern-Datei"
  #   while read pattern_file; do
  #     if [[ ! -z $pattern_file ]]; then
  # 
  #       keyword_for_pattern=$(sed -e "s/^$category//" <<< "$keyword" | sed -e "s/-/ - /")
  #       keyword_for_pattern=$(sed -e "s/^\\$category_separator//" <<< "$keyword_for_pattern")
  #       
  #       patterns=$("$script_path/../functions/getPattern.sh" "$pattern_file")
  #       
  #       
  #       while read -r pattern; do
  #         result=$(grep -E "$pattern" <<< " $keyword_for_pattern ")
  #         if [[ $result != "" ]]; then
  #           echo "$pattern_file"
  #         fi
  #       done <<< "$patterns"
  #     fi
  #   done <<< "$pattern_files"
  # )
  # 
  # pattern_files_hit=$(sed -e '/^$/d' <<< "$pattern_files_hit")

  if [[ $pattern_files_hit == "" ]]; then
    echo "[$count/$countCalibreIds] Calibre ID: $calibre_id - Es wurde kein Suchmuster gefunden, welches auf \"$keyword\" passt."
  else
    logDebug "\"$keyword\" für Calibre-ID \"$calibre_id\" wurde erstellt durch \"$pattern_files_hit\""
    dont_ask_file=""
    ignore_file=""
    while read pattern_file_hit; do
      # echo "$pattern_file_hit"
      false_positive_file=${pattern_file_hit//pattern\//false_positive\/}
      # echo "$false_positive_file"
      true_positive_file=${pattern_file_hit//pattern\//true_positive\/}
      true_positive_file=${true_positive_file//pattern/list}
      # echo "$true_positive_file"

      category=$(look category "$pattern_file_hit" | cut -d '=' -f 2-)
      # keyword=$(sed -e "s/^$category//" <<< "$keyword")
      # keyword=$(sed -e "s/^\\$category_separator//" <<< "$keyword")
      grep_true_positive_keyword=""
      if [[ -f $true_positive_file ]]; then
        if [[ ! -z $given_category ]]; then
          grep_true_positive_keyword="$grep_true_positive_keyword$given_category$category_separator"
        else
          grep_true_positive_keyword="$grep_true_positive_keyword$category$category_separator"
        fi
        grep_true_positive_keyword="$grep_true_positive_keyword$keyword"
        grep_true_positive_keyword=$(sed -e 's/\//\\\//g' <<< "$grep_true_positive_keyword" | sed -e 's/\./\\\./g')
        true_positive=$(grep -l "^$calibre_id=$grep_true_positive_keyword\$" "$true_positive_file")
      else
        true_positive=""
      fi
      
      if [[ ! -z $true_positive ]]; then
        logInfo "\"$keyword\" wurde in \"$true_positive\" gefunden, keine Aktion nötig."
      else
        pdf_path=$(find "$working_path" -type f -name '*.pdf')
        hr_txt_path=${pdf_path//.pdf/.human-readable.txt}
        txt_path=${pdf_path//.pdf/.txt}

        keyword_pattern=""
        if [[ ! -z $category ]]; then
          keyword_pattern="$keyword_pattern$category$category_separator"
        fi
        keyword_pattern="$keyword_pattern$keyword"
        keyword_pattern=$(sed -e 's/\//\\\//g' <<< "$keyword_pattern" | sed -e 's/\./\\\./g')

        grep_by=$(sed -e "s/^$category\\$category_separator//" <<< "$keyword" | sed -e "s/-/ - /" | sed -e 's/\//\\\//g' | sed -e 's/\./\\\./g' | sed -E "s/^(.*)\$/[[:space:]]\1[[:space:]]/g")
        # echo "###$grep_by"
        egrep -anET -C 5 "$grep_by" "$txt_path"

        ignore_file="$false_positive_file"
        dont_ask_file="$true_positive_file"

        if [[ -z $category ]]; then
          true_positive_keyword="$keyword"
        else
          true_positive_keyword="$category$category_separator$keyword"
        fi
        

        echo
        echo "1) Nicht mehr fragen"
        echo "2) Schlüsselwort dauerhaft entfernen und Aktualisierung durchführen"
        echo "3) Schlüsselwort dauerhaft entfernen, aber keine Aktualisierung durchführen"
        echo "4) PDF ansehen \"$pdf_path\""
        echo "5) Original TXT ansehen \"$hr_txt_path\""
        echo "6) Gekürzten TXT ansehen \"$txt_path\""
        echo "7) Verzeichnis öffnen \"$working_path\""
        echo "8) Nichts tun"
        while true; do
          read -p "Bitte wählen: " input < /dev/tty
          case $input in
              [1]* )
                echo "$calibre_id=$true_positive_keyword" >> "$dont_ask_file"
                logDebug "Nach \"$keyword\" für Calibre-ID \"$calibre_id\" wird nicht mehr gefragt: \"$calibre_id=$true_positive_keyword\" in \"$dont_ask_file\""
                break;;
              [2]* )
                echo "$calibre_id=^($keyword_pattern)\$" >> "$ignore_file"
                extract_and_write_keywords_into_calibre "$working_path"
                logDebug "\"$keyword\" für Calibre-ID \"$calibre_id\" wurde dauerhaft entfernt: \"$calibre_id=^($keyword_pattern)\$\" in \"$ignore_file\""
                break;;
              [3]* )
                echo "$calibre_id=^($keyword_pattern)\$" >> "$ignore_file"
                logDebug "\"$keyword\" für Calibre-ID \"$calibre_id\" wurde zur dauerhaften Entfernung vorgemerkt: \"$calibre_id=^($keyword_pattern)\$\" in \"$ignore_file\""
                break;;
              [4]* )
                echo "Öffne \"$pdf_path\""
                xdg-open "$pdf_path" > /dev/null 2>&1
                ;;
              [5]* )
                echo "Öffne \"$hr_txt_path\""
                xdg-open "$hr_txt_path" > /dev/null 2>&1
                ;;
              [6]* )
                echo "Öffne \"$txt_path\""
                xdg-open "$txt_path" > /dev/null 2>&1
                ;;
              [7]* )
                echo "Öffne \"$working_path\""
                xdg-open "$working_path" > /dev/null 2>&1
                ;;
              [8]* ) break;;
              * ) echo "Ungültige Auswahl";;
          esac
        done
      fi
    done <<< "$pattern_files_hit"
  fi
done <<< "$calibre_ids"

exit 0
